---
title: "01 Data Visualization"
webr:
  packages: ["palmerpenguins"]
  autoload-packages: true
---

---

This chapter accompanies [1 Data Visualization](https://r4ds.hadley.nz/data-visualize) in R4DS.

## Chapter Follow-Along

Use the following code cell to follow along while reading the chapter. (You are encouraged to do this in RStudio instead!)

These notes use something called `webr`, which allows R to run in your browser (no installation needed)! However, it also means that the packages must be installed every time you reload your browser. Run the following cell once and it will show package installation output, then run it again and that output will be gone.

```{webr-r}
#| label: follow-along
library(palmerpenguins)
library(ggplot2)
library(dplyr)

glimpse(penguins)

ggplot(penguins, mapping = aes(x = flipper_length_mm))
```


## Exercises

### 1.2 First Steps

1. How many rows are in `penguins`? How many columns?

```{webr-r}
#| label: rows-and-cols

```

2. What does the `bill_depth_mm` variable in the `penguins` data frame describe? Read the help for `?penguins` to find out.

```{webr-r}
#| label: 
?penguins
```

3. Make a scatterplot of `bill_depth_mm` vs. `bill_length_mm`. That is, make a scatterplot with `bill_depth_mm` on the y-axis and `bill_length_mm` on the x-axis. Describe the relationship between these two variables.

```{webr-r}
#| label: bill-vs-bill

???
```

4. What happens if you make a scatterplot of `species` vs. `bill_depth_mm`? What might be a better choice of geom?

```{webr-r}
#| label: species-scatterplot
ggplot(penguins) +
  aes(x = bill_depth_mm, y = species) +
  geom_point()
```

5. Why does the following give an error and how would you fix it?

```{webr-r}
#| label: error
ggplot(data = penguins) + 
  geom_point()
```

6. What does the `na.rm` argument do in `geom_point()`? What is the default value of the argument? Create a scatterplot where you successfully use this argument set to `TRUE`.

```{webr-r}
#| label: 
ggplot() +
  geom_point(???)
```

7. Add the following caption to the plot you made in the previous exercise: `“Data come from the palmerpenguins package.”` Hint: Take a look at the documentation for labs().

```{webr-r}
#| label: bill-vs-bill
ggplot(palmerpenguins, mapping = aes(???)) +
  geom_???(???)
```

8. Recreate the [following visualization](https://r4ds.hadley.nz/data-visualize#exercises). What aesthetic should `bill_depth_mm` be mapped to? And should it be mapped at the global level or at the geom level?

```{webr-r}
#| label: colour-by-bill_depth_mm
ggplot(palmerpenguins, mapping = aes(???)) +
  geom_???(???)
```

9. Run this code in your head and predict what the output will look like. Then, run the code in R and check your predictions. (*Note: ggplot2 accepts either "`color`" or "`colour`" as an argument. I am changing all instances to the Canadian spelling.*)

```{webr-r}
#| label: predict-island

ggplot(
    data = penguins,
    mapping = aes(x = flipper_length_mm, y = body_mass_g, colour = island)
) +
    geom_point() +
    geom_smooth(se = FALSE)
```

10. Will these two graphs look different? Why/why not?

```{webr-r}
#| label: guess-differences
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point() +
  geom_smooth()

ggplot() +
  geom_point(
    data = penguins,
    mapping = aes(x = flipper_length_mm, y = body_mass_g)
  ) +
  geom_smooth(
    data = penguins,
    mapping = aes(x = flipper_length_mm, y = body_mass_g)
  )
```












### 1.4 Visualizing distributions

1. Make a bar plot of `species` of penguins, where you instead assign `species` to the `y` aesthetic. How is this plot different?

```{webr-r}
#| label: species-bar
# Code from earlier in the chapter:
ggplot(penguins, aes(x = fct_infreq(species))) +
  geom_bar()
```

2. How are the following two plots different? Which aesthetic, `colour` or `fill`, is more useful for changing the colour of bars?

```{webr-r}
#| label: colour-vs-fill
ggplot(penguins, aes(x = species)) +
  geom_bar(colour = "red")

ggplot(penguins, aes(x = species)) +
  geom_bar(fill = "red")
```

4. Make a histogram of the `carat` variable in the `diamonds` dataset that is available when you load the `ggplot2` package. Experiment with different `binwidth`s. What binwidth reveals the most interesting patterns?

```{webr-r}
#| label: diamonds-carat-hist
glimpse(diamonds)
```

### 1.5.5 Visualizing Relationships

1. The `mpg` data frame that is bundled with the `ggplot2` package contains 234 observations collected by the US Environmental Protection Agency on 38 car models. Which variables in `mpg` are categorical? Which variables are numerical? (Hint: Type `?mpg` to read the documentation for the dataset.) How can you see this information when you run mpg?

```{webr-r}
#| label: mpg-types
?mpg
```

2. Make a scatterplot of `hwy` vs. `displ` using the `mpg` data frame. Next, map a third, numerical variable to `colour`, then `size`, then both `colour` and `size`, then `shape`. How do these aesthetics behave differently for categorical vs. numerical variables?
3. In the scatterplot of hwy vs. displ, what happens if you map a third variable to linewidth?
4. What happens if you map the same variable to multiple aesthetics?

```{webr-r}
#| label: shape-scale-colour

# Note: The aes() call can be a separate part of the ggplot() pipeline
# In this case, it is added at the *global* level!
ggplot(mpg) +
  aes(x = ???, y = ???, colour = ???, size = ???, shape = ???)
  geom_point()
```

5. Make a scatterplot of `bill_depth_mm` vs. `bill_length_mm` and colour the points by `species`. What does adding colouring by `species` reveal about the relationship between these two variables? What about faceting by `species`?

```{webr-r}
#| label: colour-by-species

```

6. Why does the following yield two separate legends? How would you fix it to combine the two legends?

```{webr-r}
#| label: 
ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm, y = bill_depth_mm, 
    colour = species, shape = species
  )
) +
  geom_point() +
  labs(colour = "Species")
```

7. Create the two following stacked bar plots. Which question can you answer with the first one? Which question can you answer with the second one?

```{webr-r}
#| label: 
ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar(position = "fill")
ggplot(penguins, aes(x = species, fill = island)) +
  geom_bar(position = "fill")
```

